### PR TITLE
corrects the ellipse rotation for paste

### PR DESCRIPTION
**Pull request by bhattigurjot**
Solves #234

### CODE REVIEW

**Comment by CharuChopra84** [comment]
It doesn't work for me. Please check it once

**Comment by bhattigurjot** [comment]
Do mention what doesn't work. Or the screenshot if some glitch is there.

**Comment by CharuChopra84** [comment]
Before pasting ellipse is as follows:
screenshot from 2015-01-08 22 13 26
After pasting it appears as follows:
screenshot from 2015-01-08 22 13 47

**Comment by kamalpreetgrewal** [comment]
What I have figured out is that there is no glitch if you do so in all the cases:
Create an ellipse say ellipse1, paste it. It would be pasted as expected and let this be ellipse2. Now copy ellipse2 and paste it. Then there is unexpected direction. 

Also I figure it depends on the angle of ellipse too to determine what happens next as has been currently done. 

The case above scenario worked is:
screenshot from 2015-01-09 00 11 53

**Pull request closed without merging**
